// Unit 10: Automated Testing Tools (Chapter 11, pp.159–175)
EXTRA_UNITS.push({
id:10, concepts:[
{title:"Overview of Automated Testing Tools",ref:"pp.159–160",content:`<p>Over <strong>300</strong> commercial test tool products exist. Each assists testers with one or more activities, but <strong>no single tool</strong> covers all testing needs.</p><div class="callout important"><strong>Critical insight:</strong> Automated tools are NOT always required. There are situations where tools are inappropriate, disadvantageous, and expensive. The first decision is <strong>whether</strong> to use tools — only then does tool choice arise.</div><p>The "hammer" warning: <em>"When you first learn how to use a hammer, everything looks like a nail."</em> Don't let tool euphoria cloud rational decision-making.</p><div class="zh-note">300+种测试工具，但没有一个能覆盖所有需求。先决定"是否"用工具，再决定"用哪个"。</div>`},
{title:"The Record/Playback Paradigm",ref:"pp.162–164",content:`<p>The core mechanism of automated test tools — a <strong>3-step repeatable process</strong>:</p><ol style="padding-left:20px;"><li><strong>Step 1:</strong> An end-user operates the Application Under Test (<span class="key-term">AUT</span>) to perform a business task.</li><li><strong>Step 2:</strong> The test tool <strong>"watches"</strong> and records the user's actions into a <span class="key-term">script file</span>.</li><li><strong>Step 3:</strong> The tool <strong>plays the script back</strong>, precisely recreating the user's operations without human intervention.</li></ol><p>All three steps are designed to be <strong>repeatable</strong>. Scripts can be re-recorded when the software changes, and replayed many times for verification.</p><div class="zh-note">录制/回放：用户操作→工具录下来存为脚本→工具回放脚本自动执行，无需人工干预。</div>`},
{title:"Script Language & Data-Driven Testing",ref:"pp.163–164",content:`<p>No universal script language exists, but skills transfer substantially between vendors. Two design approaches:</p><ul><li><strong>Custom language</strong> from scratch with added flow-control (loops, conditions)</li><li><strong>Extended standard language</strong> — PASCAL, C, Visual Basic, or Java with added test commands</li></ul><p><span class="key-term">Data-driven execution</span>: Record a simple action (e.g., login with one user ID), then replace typed values with references to a data file containing hundreds/thousands of values. One script → millions of test permutations.</p><p>Example: 1 script × 2,000 zip codes × 4 customer types × 5,000 items = <strong>40,000,000 permutations</strong>.</p>`},
{title:"Two Touchpoint Paradigms",ref:"pp.164–168",content:`<p>A <span class="key-term">touchpoint</span> = where the tool "probes" the system.</p><p><strong>Paradigm 1 — Functional (foreground) testing:</strong></p><ul><li>Tool operates at the <strong>client workstation</strong>, directly controlling the UI as if an end-user were sitting there</li><li>Uses the user's keyboard/mouse/screen</li></ul><p><strong>Paradigm 2 — Performance (background) testing:</strong></p><ul><li>Tool operates on a <strong>separate server</strong>, capturing messages and timing between client and server</li><li>Does NOT touch the user's workstation directly</li></ul><div class="callout">Good news: the two paradigms <strong>don't conflict</strong>. Both can run simultaneously in the same testing environment.</div>`},
{title:"Benefits of Testing Tools (4 key areas)",ref:"pp.169–173",content:`<ul><li><strong>1. Repeatability ROI:</strong> If a script runs <strong>3+ times</strong>, tool cost < manual cost. After 3 executions, automated testing starts saving money. Manual testing costs grow linearly with no economies of scale.</li><li><strong>2. Repeatability precision:</strong> Tools execute scripts with <strong>explicit data, no human error</strong>. No skipped steps, no missed pages. This makes defect reproduction much easier for developers.</li><li><strong>3. Hidden results verification:</strong> Tools can observe both the user-visible AND hidden responses (database updates, control states) that manual testing cannot easily check.</li><li><strong>4. Impossible manual tests:</strong> Any workload beyond <strong>100 active transactions</strong> cannot be tested manually. Performance tools can drive workloads of <strong>thousands to 500,000+</strong> transactions.</li></ul><div class="zh-note">自动化工具四大优势：重复执行省钱(3次以上)、精确无人为误差、能验证隐藏结果、能测手动不可能的大负载。</div>`},
{title:"Liabilities of Testing Tools",ref:"pp.173–175",content:`<p>Costs often overlooked:</p><ul><li><strong>Price tag:</strong> Several thousand to almost $1 million. Plus licensing per computer, per tester, or per peak session.</li><li><strong>Hardware:</strong> Performance tools need dedicated server(s) and possibly extra network equipment.</li><li><strong>Installation time:</strong> Adds to environment setup schedule — may delay test execution start.</li><li><strong>Training:</strong> Testers need prior experience or specific training for each tool.</li><li><strong>One-off cost:</strong> First-time script writing is expensive. ROI only comes from <strong>repeat use</strong>.</li><li><strong>Change fragility:</strong> If the software changes (even 1 pixel shift), scripts may need re-recording. Coordinate-based recording is precise but fragile; property-based recording is flexible but also breaks with property changes.</li></ul><div class="callout important"><strong>Bottom line:</strong> Only use tools when the <strong>repeat usage</strong> justifies the setup cost, OR when the testing is <strong>impossible to do manually</strong>.</div>`}
],quiz:[
{type:"mc",q:"The first decision about automated testing tools should be:",options:["Which vendor to choose","Whether tools are appropriate for this project","Which programming language the script uses","How many licenses to buy"],answer:1,explanation:"First decide WHETHER to use tools. Only after appropriateness is confirmed does tool choice arise."},
{type:"mc",q:"The Record/Playback paradigm has how many steps?",options:["2","3","4","5"],answer:1,explanation:"3 steps: (1) User operates the AUT, (2) Tool records actions as a script, (3) Tool plays back the script."},
{type:"mc",q:"Automated testing tools become cost-effective after how many script executions?",options:["1 execution","2 executions","3 or more executions","10 or more executions"],answer:2,explanation:"After 3+ executions, the accumulated cost of automated testing falls below manual testing cost. ROI comes from repetition."},
{type:"sa",q:"Explain data-driven execution and why it's powerful.",sampleAnswer:"Data-driven execution allows the tester to record one simple action (like a login), then replace the typed values with references to data files containing hundreds or thousands of values. When replayed, the script automatically tests all permutations. For example, 1 script with 2,000 zip codes × 4 customer types × 5,000 item codes = 40 million test permutations from a single recording.",keywords:["record","replace","data file","permutations","values","replay","millions"]},
{type:"mc",q:"Performance testing tools workloads beyond what threshold cannot be tested manually?",options:["10 transactions","50 transactions","100 transactions","1,000 transactions"],answer:2,explanation:"Any workload beyond 100 active transactions cannot be tested manually. Performance tools can handle thousands to 500,000+."},
{type:"sa",q:"Name at least 3 hidden costs or liabilities of automated testing tools.",sampleAnswer:"1. High price tag (thousands to $1 million) plus licensing fees.\n2. Additional hardware needed (performance tool servers, network equipment).\n3. Installation time delays the testing environment setup.\n4. Training costs for testers to learn each specific tool.\n5. Script fragility — even a 1-pixel UI change can break scripts.\n6. First-time script creation is expensive; ROI only comes from repeat use.",keywords:["price","hardware","installation","training","fragile","change","repeat","expensive"]}
]});

// ============================================================
// Unit 10: Automated Testing Tools
// ============================================================
MODERN_NOTES['10-0'] = {
  title: 'AI-powered testing: the 2026 reality check',
  year: '2026',
  content: 'Gartner predicts 70% of DevOps orgs will use AI-augmented testing tools by 2026. But the industry is sobering up: the #1 concern among 40,000+ testers is "Does AI-generated code actually reduce the need for testing, or does it demand MORE?" The answer: <strong>more testing, not less</strong>. AI tools are partners for repetitive tasks, not replacements for human judgment.'
};
MODERN_NOTES['10-1'] = {
  title: 'Self-healing tests + low-code/no-code',
  year: '2026',
  content: 'The book\'s "script fragility" problem (1 pixel change breaks scripts) is being addressed by <strong>self-healing tests</strong> (Testim, Mabl) that automatically adjust selectors when the UI changes. <strong>Low-code/no-code platforms</strong> (Katalon, BugBug) let non-programmers build tests via drag-and-drop. But the book\'s warning still applies: evaluate whether tools are appropriate BEFORE choosing one.'
};
MODERN_NOTES['10-4'] = {
  title: '3x ROI rule still holds — with a twist',
  year: '2026',
  content: 'The book\'s "3+ runs to break even" is still accurate. Modern twist: CI/CD runs test suites <strong>hundreds of times per day</strong>, so ROI is nearly instant for automated tests in a CI/CD pipeline. But the <strong>first-time cost</strong> is still real: writing good automated tests requires skill, and AI-generated tests still need human review. Maintenance cost is now the biggest concern, not creation cost.'
};
