// Unit 7: Structural (Non-Functional) Testing (Chapter 8, pp.122–127) — Module 7
EXTRA_UNITS.push({
id:7, concepts:[
{title:"🎯 Learning Objectives",ref:"Module 7",content:`<p>By the end of this chapter you should be able to:</p><ul><li>Define <strong>structural (non-functional) testing</strong> as testing the software <strong>platform</strong> that supports the application</li><li>Distinguish <strong>functional (WHAT)</strong> from <strong>non-functional (HOW WELL)</strong> testing</li><li>Apply the textbook's structural-testing techniques: <strong>interface, security, installation, smoke, administration, backup &amp; recovery</strong></li><li>Recognize the wider NFT family — <strong>reliability, usability, portability</strong> — and the certification path (ISTQB)</li><li>Use real-world failures (LA ATC 2004) to argue for long-duration + backup-recovery testing</li></ul><div class="zh-note">本章目标:理解结构(非功能)测试 = 测平台 · 区分"功能(做什么)"vs"非功能(做得多好)" · 掌握 6 类核心非功能测试(接口/安全/安装/冒烟/管理/备份恢复) · 了解可靠性/易用性/可移植性 · 用真实案例(LA 空管 2004)论证长时间+备份测试的必要。</div>`},
{title:"What is Structural (Non-Functional) Testing?",ref:"pp.122–123",content:`<p>Structural testing validates the <span class="key-term">software platform</span> — the support software that enables the application the user touches to run: OS, security, connectivity, data management.</p><p>The platform is <strong>NOT written for one specific app</strong>; it's a <strong>generic capability</strong> that supports many apps at once. That makes it a possible <strong>point of failure</strong> when new software runs on it.</p><p>The big distinction:</p><table style="width:100%;border-collapse:collapse;margin:14px 0;font-size:13.5px;"><thead><tr><th style="padding:10px;text-align:left;background:var(--green-bg);color:var(--green);font-weight:700;border-bottom:2px solid var(--green);">Functional testing</th><th style="padding:10px;text-align:left;background:var(--blue-bg);color:var(--blue);font-weight:700;border-bottom:2px solid var(--blue);">Non-Functional (Structural)</th></tr></thead><tbody><tr><td style="padding:8px 10px;border-bottom:1px solid var(--border-light);">Checks <strong>WHAT</strong> the software does</td><td style="padding:8px 10px;border-bottom:1px solid var(--border-light);">Checks <strong>HOW WELL</strong> it does it</td></tr><tr style="background:var(--bg-warm);"><td style="padding:8px 10px;">Features &amp; business functions</td><td style="padding:8px 10px;">Performance, security, usability, reliability</td></tr></tbody></table><p>The authors prefer <span class="key-term">structural testing</span> over the synonym "non-functional testing" to avoid the joke: <em>"If it's non-functional, doesn't that mean it doesn't work?!"</em></p><div class="callout">Think of structural testing as a <strong>buffet, not a strict diet</strong> — apply only the techniques relevant to YOUR application's platform components.</div><div class="zh-note">结构测试=测试支撑应用运行的平台软件(操作系统、安全、网络、数据库)。功能测试问"做什么",非功能测试问"做得好不好"(性能/安全/易用/可靠)。平台是通用的、给很多应用共用,所以是潜在故障点。</div>`},
{title:"📊 Why Non-Functional Testing Matters",ref:"Module 7",content:`<p>Non-functional testing is <strong>just as important as functional testing</strong> — both ensure the product works as it should, but NFT checks the aspects functional tests don't cover. Seven reasons it matters:</p><ol style="padding-left:20px;"><li>Ensures the app performs <strong>efficiently under real-world conditions</strong></li><li>Identifies <strong>performance bottlenecks</strong> before deployment</li><li>Improves <strong>reliability and availability</strong></li><li>Enhances <strong>user experience</strong> (usability, responsiveness)</li><li>Strengthens <strong>security</strong> against internal &amp; external threats</li><li>Reduces <strong>production risks</strong> and post-release failures (backup &amp; recovery)</li><li>Helps meet <strong>business goals &amp; SLAs</strong> (Service Level Agreements)</li></ol><div class="callout important">The support software <strong>cannot compensate</strong> for a poor application — but it <strong>can detract</strong> from a good one. A great app on a broken platform still fails. The motivation for structural testing is to validate this "application enabler."</div><div class="zh-note">非功能测试和功能测试一样重要。七大价值:真实负载下高效、提前发现性能瓶颈、提升可靠性/可用性、改善体验、加强安全、降低上线风险、满足SLA。好平台救不了烂应用,但烂平台能拖垮好应用。</div>`},
{title:"Why White/Black Box Don't Fully Apply",ref:"pp.122–123",content:`<p>Two key limitations when testing the platform:</p><ul><li><strong>No source code:</strong> Platform components are prepackaged, so <strong>white box</strong> techniques can't be used.</li><li><strong>Not user-visible:</strong> Platform behavior is rarely observed directly by end users, so most <strong>black box</strong> techniques don't apply either — <em>except intuition and experience</em>, which still help.</li></ul><p>This area relies heavily on the tester's <strong>system administrator experience</strong>, or collaboration with system administrators.</p><div class="zh-note">平台是预打包的(没源码)→白盒用不了;用户也看不到平台内部→大多数黑盒也用不了,只有"经验/直觉"还能用。所以这块很依赖系统管理员的经验。</div>`},
{title:"Interface Testing (4-Step + Stubbing)",ref:"pp.123–124",content:`<p><span class="key-term">Interface testing</span> verifies the data exchanged between the app and platform components: <strong>data files, APIs, database requests, network transfers</strong>. The textbook's <strong>4-step approach</strong>, with a payment/shipping example:</p><ol style="padding-left:20px;"><li><strong>Validate outgoing data</strong> (transfer inhibited) — app produces data, check format is correct. <em>Verify order amount &amp; customer details before sending to the payment gateway.</em></li><li><strong>Validate platform processing</strong> — remove the inhibitor, confirm the platform handles the data. <em>Check the payment gateway processes the payment.</em></li><li><strong>Validate incoming data via a STUB</strong> — manually substitute test data instead of a live feed. <em>Simulate shipping-status data to test order tracking.</em></li><li><strong>Validate live data exchange</strong> — connect live, rerun end-to-end. <em>Retrieve real tracking info from the shipping provider.</em></li></ol><div class="callout"><strong>Why use a stub?</strong> The real service may be unavailable · testing can begin <strong>before</strong> the real API is finished · it isolates whether a defect is in <strong>your app</strong> or the <strong>external system</strong>.</div><p style="font-size:13px;"><strong>Tools:</strong> Postman (request/response), SoapUI (SOAP &amp; REST), Swagger/OpenAPI (spec validation), JMeter (interface + performance), SQL tools (DB interfaces).</p><div class="zh-note">接口测试四步:① 测应用产出的数据格式(先不传)② 放开传输,测平台能否正确处理 ③ 用桩(stub)假数据测应用接收 ④ 全连通跑真数据。用桩的原因:真服务没好/不可用、能提前测、便于定位bug在哪边。工具:Postman/SoapUI/Swagger/JMeter。</div>`},
{title:"Security Testing",ref:"pp.124–125",content:`<p><span class="key-term">Security testing</span> checks whether software is vulnerable to attack, controls access, protects data, and enforces permissions — users can only reach what their <strong>role/level</strong> allows. It's non-functional: it checks the app is <strong>designed &amp; configured correctly (the "how")</strong>, not just that functions work.</p><p>Use <span class="key-term">equivalence classes</span> for security levels — an e-commerce example:</p><ul><li><strong>Level 1 — Customer:</strong> browse products, place orders</li><li><strong>Level 2 — Store Manager:</strong> view orders, update stock</li><li><strong>Level 3 — Admin:</strong> manage users &amp; system settings</li></ul><p>Instead of testing every ID/password (thousands), pick <strong>representative valid users per level (positive)</strong> AND <strong>invalid users (negative)</strong>. Negative checks must <em>block</em>:</p><ul><li>Wrong password → rejected · Customer opens an admin page → blocked</li><li>Manager deletes users → denied · Tampered request faking a role → ignored</li></ul><div class="callout important"><strong>Beyond login:</strong> test <strong>password encryption</strong> (no plain-text in storage/transmission) and enforce permissions <strong>continuously during the session</strong>, not just at login. And don't forget <strong>security performance</strong> — security adds overhead; turning it on right before go-live causes day-one slowdowns.</div><p style="font-size:13px;"><strong>Tools:</strong> Burp Suite, OpenSSL (certs/encryption), Nmap (ports), Wireshark (traffic), Postman (auth/tokens).</p><div class="zh-note">安全测试:按角色/等级控制访问。用等价类分级(顾客/店长/管理员),每级选少量"合法用户(正向)+非法用户(负向)"。负向必须被拦:错密码、越权访问、改请求伪造角色。还要测密码加密、会话中持续校验权限,别只测登录。工具:Burp/Nmap/Wireshark。</div>`},
{title:"Installation, Smoke Test & Rollback",ref:"pp.125–126",content:`<p><span class="key-term">Installation testing</span> — validate recipients can install the software and make it ready for use. Set up a test environment that <strong>mirrors production exactly</strong>, run the installer as written. For a new Microsoft Teams release, check:</p><ul style="font-size:13.5px;"><li>Installs successfully? Shortcuts created? App launches?</li><li>Upgrade from the previous version works? Dependencies connected?</li><li>Can it be <strong>completely uninstalled</strong>?</li></ul><p><span class="key-term">Rollback</span> — if an install/upgrade fails halfway, the system must <strong>restore to the previous version</strong>. <em>e.g. installing v2.0 over v1.0 fails midway → rollback removes the changes → system is back on v1.0.</em></p><p><span class="key-term">Smoke test</span> — after install, verify the software can be <strong>configured properly</strong>. Named after hardware engineering: plug in new equipment, look for smoke; none → start using it. The planner identifies the <strong>10 most likely configuration combinations</strong> for the most important customer installations and runs minimal verification of each. It is <strong>not exhaustive</strong> like regression testing.</p><div class="zh-note">安装测试:在"和生产一模一样"的环境按文档跑安装(装好没?快捷方式?能启动?能升级?依赖?能彻底卸载?)。回滚:升级失败要能退回旧版本。冒烟测试:装好后快速验证最可能的10种配置能否正常运行——不是穷举,只是"能不能基本跑起来"。</div>`},
{title:"Administration Testing",ref:"pp.126–127",content:`<p><span class="key-term">Administration testing</span> verifies the <strong>support activities</strong> performed by system administrators (not end users) after installation. It's an <strong>extension of functional testing</strong> applied to back-office operations:</p><ul><li>Adding / modifying / deleting <strong>users</strong></li><li>Assigning <strong>roles &amp; permissions</strong></li><li>Configuring <strong>security settings</strong></li><li>Creating customer / product / <strong>master data files</strong></li><li>Applying <strong>updates &amp; patches</strong>; managing system configuration</li></ul><p><em>Example — a Learning Management System:</em> create instructor &amp; student accounts, assign access rights, and verify every administrative action behaves as expected.</p><div class="callout"><strong>Dev-order trick (textbook):</strong> if admin components are built <strong>first</strong>, successful admin-test results become the <strong>starting point</strong> for business-function testing. If built <strong>second</strong>, the manual setup files used to test business functions become the <strong>expected results</strong> for the admin tests.</div><div class="zh-note">管理测试:测管理员的后台支持工作(增删改用户、分配角色权限、配安全、建主数据、打补丁)。是功能测试在"业务支持活动"上的延伸。例:LMS里建师生账号、配权限并验证。</div>`},
{title:"Backup & Recovery Testing",ref:"pp.126–127",content:`<p>Sooner or later, <strong>all business software fails</strong>. The financial damage is directly proportional to how much effort went into minimizing it. <span class="key-term">Backup &amp; recovery testing</span> assesses whether you can reliably replicate data <em>and</em> retrieve it when needed.</p><p><strong>The test process:</strong> perform several backups → interrupt the application <strong>abnormally</strong> → restore using <strong>only the backups</strong> → validate recovered data against the expected <strong>pre-failure state</strong>.</p><table style="width:100%;border-collapse:collapse;margin:12px 0;font-size:13.5px;"><tbody><tr style="background:var(--bg-warm);"><td style="padding:8px 10px;font-weight:700;color:var(--accent-dim);width:120px;">Backup</td><td style="padding:8px 10px;">Making a <strong>copy</strong> of the data</td></tr><tr><td style="padding:8px 10px;font-weight:700;color:var(--accent-dim);">Recovery</td><td style="padding:8px 10px;">Using that copy to <strong>restore</strong> the system after a failure</td></tr></tbody></table><div class="callout important"><strong>The critical test most companies SKIP:</strong> they validate backup <strong>procedures</strong> but never test the <strong>restore</strong>. The first real restore — empty files, bad rotation — often fails. It is not enough to take backups; you must <strong>test restoring them</strong>. A "career-altering experience."</div><p style="font-size:13px;"><strong>Tools:</strong> Commvault, AWS Backup, Azure Backup (cloud backup &amp; restore testing).</p><div class="zh-note">备份=复制数据;恢复=用备份还原系统。测法:多次备份→异常中断应用→只用备份还原→对比故障前状态。很多公司只测备份不测恢复,真出事第一次还原才发现备份是空的/轮换错了。光备份没用,必须测"能不能还原回来"。</div>`},
{title:"⚙️ More NFT Types: Reliability · Usability · Portability",ref:"Module 7",content:`<p>Beyond the textbook's core set, the non-functional family includes several quality dimensions. (<strong>Performance testing</strong> is also NFT — it gets its own Unit 8.)</p><table style="width:100%;border-collapse:collapse;margin:14px 0;font-size:12.5px;"><thead><tr style="background:var(--accent-bg);border-bottom:2px solid var(--accent);"><th style="padding:8px;text-align:left;color:var(--accent-dim);">Type</th><th style="padding:8px;text-align:left;color:var(--accent-dim);">Verifies</th><th style="padding:8px;text-align:left;color:var(--accent-dim);">Example</th></tr></thead><tbody><tr style="border-bottom:1px solid var(--border-light);"><td style="padding:8px;color:var(--blue);font-weight:700;">Reliability</td><td style="padding:8px;">Runs <strong>consistently without failure over time</strong> (reliability, availability, recoverability)</td><td style="padding:8px;font-style:italic;">Banking app runs 72h non-stop: no crashes, data corruption, or interruptions; Black-Friday shop stays up for days</td></tr><tr style="background:var(--bg-warm);border-bottom:1px solid var(--border-light);"><td style="padding:8px;color:var(--purple);font-weight:700;">Usability</td><td style="padding:8px;">How <strong>easy, efficient &amp; user-friendly</strong> it is</td><td style="padding:8px;font-style:italic;">New user can register, search "laptop", add to cart &amp; check out <strong>without help</strong>; mobile-friendly; clear errors</td></tr><tr><td style="padding:8px;color:var(--green);font-weight:700;">Portability</td><td style="padding:8px;">Runs across <strong>different environments with minimal change</strong></td><td style="padding:8px;font-style:italic;">Same site works on Windows/macOS/Linux, Chrome/Firefox/Safari, desktop/mobile; migrate AWS → Azure</td></tr></tbody></table><div class="callout"><strong>Good vs poor portability:</strong> good = only a few config settings change; poor = developers must rewrite large parts. Minimal change = less coding, cost, and effort.</div><p style="font-size:13px;"><strong>Tools:</strong> Reliability → JMeter, LoadRunner, Gatling · Usability → Hotjar, Crazy Egg, UserTesting · Portability → VMware/VirtualBox, Docker, BrowserStack, CI (Jenkins/GitHub Actions).</p><div class="zh-note">其他非功能类型:可靠性(长时间不崩,如银行连跑72小时)、易用性(用户不靠帮助就能完成任务、移动端友好)、可移植性(跨OS/浏览器/设备/云,改动越少越好)。性能测试也是非功能,放在第8单元。</div>`},
{title:"🎓 ISTQB & Specialty Certifications",ref:"Module 7",content:`<p><span class="key-term">ISTQB</span> (International Software Testing Qualifications Board) is the <strong>most popular testing certification worldwide</strong>, recognized in <strong>120+ countries</strong> and trusted by employers as proof of a solid testing knowledge base.</p><table style="width:100%;border-collapse:collapse;margin:14px 0;font-size:13px;"><thead><tr style="background:var(--accent-bg);border-bottom:2px solid var(--accent);"><th style="padding:8px;text-align:left;color:var(--accent-dim);">Tier</th><th style="padding:8px;text-align:left;color:var(--accent-dim);">What it covers</th></tr></thead><tbody><tr style="border-bottom:1px solid var(--border-light);"><td style="padding:8px;font-weight:600;">Foundation</td><td style="padding:8px;">Basic testing ideas &amp; terms — the entry-level cert employers ask for</td></tr><tr style="background:var(--bg-warm);border-bottom:1px solid var(--border-light);"><td style="padding:8px;font-weight:600;">Specialty</td><td style="padding:8px;"><strong>Performance, Security, Agile, Game, AI testing</strong> &amp; other cutting-edge areas</td></tr><tr style="border-bottom:1px solid var(--border-light);"><td style="padding:8px;font-weight:600;">Advanced</td><td style="padding:8px;">Deeper test management, analysis, technical test analyst</td></tr><tr style="background:var(--bg-warm);"><td style="padding:8px;font-weight:600;">Expert</td><td style="padding:8px;">Highest level — strategic test leadership</td></tr></tbody></table><p><strong>ASTQB</strong> is the official US representative of ISTQB; exams are delivered via <strong>AT*SQA</strong>. Passing puts you on the Official U.S. List of Certified Software Testers and earns "Testing Tiers" ranking points.</p><div class="callout">Many specialty tracks (Performance, Security, AI) map directly onto the <strong>non-functional testing</strong> topics in this unit. See also the ISTQB note in <strong>Unit 1</strong>.</div><div class="zh-note">ISTQB是全球最广认可的测试认证(120+国家)。等级:Foundation(入门,背术语)→ Specialty(专项:性能/安全/敏捷/游戏/AI测试)→ Advanced → Expert。ASTQB是ISTQB的美国代表,AT*SQA负责考试。很多专项认证正好对应本单元的非功能测试。</div>`},
{title:"✈️ Real-World Disaster: LA Air Traffic Control (2004)",ref:"Case study",content:`<p>The Module 7 class activity — a textbook structural-testing failure.</p><div style="background:var(--red-bg);border-left:4px solid var(--red);padding:14px 18px;border-radius:0 8px 8px 0;margin:14px 0;"><strong style="color:var(--red);">⚠️ Scenario (Los Angeles, September 14, 2004):</strong><br><span style="font-size:13.5px;">At ~5 P.M., air traffic control <strong>lost voice communication</strong> with about <strong>400 aircraft</strong> over the southwestern US. Controllers couldn't warn pilots about routes or separation — and many planes were heading toward each other. There were several near-misses before backup radios were found.</span></div><p><strong>The cause (a platform bug):</strong> the Voice Switching &amp; Control System ran a <strong>32-bit millisecond countdown timer</strong> that hit zero after ≈<strong>49.7 days</strong> of uptime and shut the system down. The workaround was a scheduled reboot every 30 days — but a technician <strong>missed the reset</strong>, so the timer ran out. The <strong>backup system also failed</strong> moments later.</p><p><strong>How structural testing would have caught it:</strong></p><ul style="padding-left:20px;"><li><strong>Reliability / endurance testing</strong> — running the platform continuously <em>past 49.7 days</em> would have exposed the timer shutdown. (Functional tests never run that long.)</li><li><strong>Backup &amp; recovery testing</strong> — the backup failed too; testing the actual failover would have revealed it.</li><li><strong>Administration / configuration testing</strong> — relying on a fragile manual 30-day reboot is a config risk a structural review would flag.</li></ul><div class="callout important"><strong>Lesson:</strong> the worst platform bugs only appear over <strong>time and under failure</strong> — exactly what reliability and backup/recovery testing target, and exactly what functional testing misses.</div><div class="zh-note">2004年9月14日洛杉矶:语音系统32位毫秒倒计时约49.7天归零自动关机,技术员漏做30天重启→系统宕机,备份也跟着失效,约400架飞机失去通讯、多次险情。可靠性/耐久测试(连续跑超49.7天)、备份恢复测试、配置/管理测试本可发现。教训:最严重的平台bug只在"长时间+故障"下才暴露,正是功能测试测不到的。</div>`}
],quiz:[
{type:"mc",q:"Structural testing focuses on validating:",options:["Business functionality from the user's perspective","The software platform that supports the application","Source code logic coverage","Use case happy paths"],answer:1,explanation:"Structural testing validates the software platform (OS, security, connectivity, data management) that supports the application."},
{type:"mc",q:"Non-functional testing primarily checks:",options:["WHAT the software does (its features)","HOW WELL the software performs (performance, security, usability, reliability)","Only the source code","Only the user interface layout"],answer:1,explanation:"Functional = WHAT the software does. Non-functional (structural) = HOW WELL it does it — performance, security, usability, reliability."},
{type:"mc",q:"Why can't white box techniques be applied to the software platform?",options:["The platform is too simple","Platform components are prepackaged with no source code","White box is only for performance testing","The test team lacks authorization"],answer:1,explanation:"Most platform components come prepackaged without source code, making white box impossible. Of the black box techniques, only intuition and experience still apply."},
{type:"mc",q:"In interface testing, why would a tester use a STUB?",options:["To make tests run faster on the CPU","Because the real external service may be unavailable, or to start testing before the real API is finished, and to isolate where a defect is","To encrypt the data being transferred","To replace the database permanently"],answer:1,explanation:"A stub substitutes test data for a live feed: useful when the real service is unavailable, to begin testing before the real API exists, and to isolate whether a defect is in your app or the external system."},
{type:"mc",q:"Security levels (Clerk / Manager / Admin) are tested efficiently using which technique?",options:["Boundary value analysis","Equivalence classes — representative valid + invalid users per level","Path coverage","Load testing"],answer:1,explanation:"Equivalence classes group users by security level/role. Instead of testing every ID/password, pick representative valid users (positive) and invalid users (negative) per level."},
{type:"mc",q:"A view-only Clerk attempts to DELETE a record and the system must block it. This is an example of:",options:["Positive security testing","Negative security testing","Performance testing","Installation testing"],answer:1,explanation:"Negative testing confirms the system rejects unauthorized or invalid actions — a Clerk's delete attempt must be denied."},
{type:"mc",q:"In installation testing, 'rollback' refers to:",options:["Re-running all regression tests","Restoring the system to its previous version when an install/upgrade fails","Backing up the database before install","Uninstalling all dependencies"],answer:1,explanation:"Rollback restores the system to the previous working version if an installation or upgrade fails partway (e.g., v2.0 over v1.0 fails → system returns to v1.0)."},
{type:"mc",q:"The term 'smoke test' originates from:",options:["Testing fire-safety systems","Hardware engineering — plug in equipment and look for smoke","Chemical material testing","Testing smoke detectors"],answer:1,explanation:"From hardware engineering: plug in new equipment, look for smoke. None = start using it. Software equivalent: after install, verify the most likely configurations work — not exhaustive."},
{type:"mc",q:"Which statement about backup and recovery testing is correct?",options:["Validating the backup procedure is sufficient","You must also test the RESTORE process, not just the backup","Recovery testing is only needed for databases","Backups never fail if scheduled"],answer:1,explanation:"Backup = making a copy; Recovery = restoring from it. Many companies test backups but never test the restore — the first real restore often fails. You must test restoring."},
{type:"mc",q:"Which NFT type verifies the system runs continuously without failure over a long period?",options:["Usability testing","Reliability testing","Portability testing","Installation testing"],answer:1,explanation:"Reliability testing confirms stable, failure-free operation over time (reliability, availability, recoverability) — e.g., a banking app running 72 hours with no crashes."},
{type:"mc",q:"Which NFT type checks that software runs across different operating systems, browsers, devices, and clouds with minimal change?",options:["Reliability testing","Usability testing","Portability testing","Security testing"],answer:2,explanation:"Portability testing verifies the software can move across environments with minimal change. Good portability = only a few config tweaks; poor = large rewrites."},
{type:"mc",q:"ISTQB specialty certifications include which areas?",options:["Only manual testing","Performance, Security, Agile, Game, and AI testing","Only database administration","Only project management"],answer:1,explanation:"ISTQB specialty tracks cover cutting-edge areas — performance, security, Agile, game, and AI testing — many of which map directly to non-functional testing."},
{type:"mc",q:"The 2004 LA Air Traffic Control failure (a ~49.7-day uptime timer) would most likely have been caught by:",options:["A quick smoke test","Long-duration reliability / endurance testing","Static code review of the UI","Boundary value analysis on a form field"],answer:1,explanation:"The bug only appeared after ~49.7 days of continuous uptime. Only long-duration reliability/endurance testing runs long enough to expose it — functional tests never run that long."},
{type:"sa",q:"Describe the 4-step approach to interface testing.",sampleAnswer:"1. Validate outgoing data with transfer inhibited — the app produces data; check the format is correct.\n2. Remove the inhibitor — validate the receiving platform component processes the data correctly.\n3. Use a stub — manually substitute the requested data instead of a live feed; validate the app accepts it.\n4. Connect live — rerun the data requests end-to-end with live data feeds.",keywords:["outgoing","inhibit","platform processes","stub","substitute","live","end-to-end","validate"]},
{type:"sa",q:"Why is testing the RESTORE process (not just the backup) so critical? Give the risk.",sampleAnswer:"A backup is only useful if you can actually restore from it. Many companies validate that backups run but never test recovery, so the first time they restore on real data — during an emergency — it fails: empty backup files, erroneous file rotation, corrupted/incomplete copies. The process is: take backups, interrupt the app abnormally, restore using only the backups, and validate the recovered data against the expected pre-failure state. Backup = copy; Recovery = restore — and only a tested restore guarantees real recovery.",keywords:["restore","recovery","backup","interrupt","pre-failure state","empty","rotation","emergency","validate"]},
{type:"sa",q:"LA Air Traffic Control (2004): what kind of bug caused it, and which structural tests would have prevented it?",sampleAnswer:"A platform/infrastructure bug: a 32-bit millisecond countdown timer in the voice communication system reached zero after about 49.7 days of uptime and shut the system down. A required 30-day reboot was missed, and the backup system also failed, so controllers lost voice contact with ~400 aircraft. Reliability/endurance testing (running the platform continuously past 49.7 days) would have exposed the timer; backup and recovery testing would have revealed the failed failover; and administration/configuration testing would have flagged the fragile manual-reboot workaround.",keywords:["49.7 days","timer","uptime","reliability","endurance","backup","recovery","failover","platform","configuration"]},
{type:"sa",q:"List four reasons non-functional testing matters to a business.",sampleAnswer:"Any four of: 1. Ensures the app performs efficiently under real-world conditions. 2. Identifies performance bottlenecks before deployment. 3. Improves reliability and availability. 4. Enhances user experience (usability/responsiveness). 5. Strengthens security against internal/external threats. 6. Reduces production risks and post-release failures (backup & recovery). 7. Helps meet business goals and SLAs.",keywords:["performance","bottlenecks","reliability","availability","user experience","security","production risk","SLA"]},
{type:"mc",q:"SCENARIO: A hospital system shows full patient records to a lab technician, who should only see test orders. Which NFT failed?",options:["Performance testing","Security testing (access control / role permissions)","Installation testing","Portability testing"],answer:1,explanation:"Security testing — specifically role-based access control. Lab technicians (lower clearance level) should not be able to view records outside their authorized scope. This is exactly the equivalence-class testing of security levels from this chapter."},
{type:"mc",q:"SCENARIO: A web app works perfectly on Chrome but fails to render the checkout button on Safari. Which NFT type catches this?",options:["Reliability testing","Usability testing","Portability testing","Backup &amp; recovery testing"],answer:2,explanation:"Portability testing — software must run across different environments (OS, browsers, devices, clouds) with minimal change. Cross-browser issues = portability defects."},
{type:"mc",q:"SCENARIO: An airline check-in kiosk must run 24/7 for 6 months between restarts. Which NFT validates this?",options:["Smoke testing","Reliability / endurance testing","Installation testing","Usability testing"],answer:1,explanation:"Reliability testing (a.k.a. endurance / soak testing) — verifies the system runs continuously without failure over long periods. This is exactly what would have caught the LA ATC 49.7-day bug."},
{type:"sa",q:"In the LA Air Traffic Control case (2004), why didn't standard functional testing catch the 49.7-day timer bug? Which structural test would have?",sampleAnswer:"Functional testing runs tests for hours or maybe a day — never 49.7 continuous days. The bug only appeared after ~49.7 days when a 32-bit millisecond counter overflowed. Only RELIABILITY / ENDURANCE / SOAK TESTING runs the platform long enough (past 49.7 days) to expose timer overflows. Backup & recovery testing would also have caught the failed failover. Lesson: time-dependent and resource-exhaustion bugs are invisible to functional tests — only long-duration structural tests find them.",keywords:["49.7","days","timer","overflow","endurance","reliability","soak","long-duration","backup","failover"]},
{type:"mc",q:"SCENARIO: A company runs nightly backups for 2 years but never tests restoring them. The first real restore (after a disk failure) takes 4 days and recovers only partial data. What's the lesson?",options:["Run backups more often","Backup ≠ recovery — you must test the RESTORE process, not just that backups complete","Buy faster disks","Hire more DBAs"],answer:1,explanation:"The textbook's critical lesson: validating that the backup procedure RUNS is not the same as validating you can RESTORE from it. Many backups silently fail (empty files, rotation errors, corruption) and the disaster restore is the first time anyone notices."}
]});

// ============================================================
// Unit 7 INTERACTIVE — Security role/permission matrix
// (equivalence classes for security levels; positive vs negative tests)
// ============================================================
INTERACTIVES[7] = function(el) {
  const roles = [
    {name:'Clerk', lvl:'Level 1', desc:'view only'},
    {name:'Manager', lvl:'Level 2', desc:'view + update'},
    {name:'Admin', lvl:'Level 3', desc:'full control'}
  ];
  const actions = ['View data','Update data','Delete records','Manage permissions'];
  // allow[role][action]
  const allow = [
    [true,  false, false, false],
    [true,  true,  false, false],
    [true,  true,  true,  true ]
  ];
  let selR = 1, selA = 2; // default: Manager tries Delete (a deny)
  function render() {
    const ok = allow[selR][selA];
    const c = ok ? '#3d8b5a' : '#c25450';
    let h = '<p style="font-size:13px;color:var(--text-dim);margin-bottom:14px;">Role-based access control tested with <strong>equivalence classes</strong>. Click any cell: green = allowed (positive test), red = blocked (negative test).</p>';
    // matrix
    h += '<div style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:12.5px;min-width:420px;">';
    h += '<thead><tr><th style="padding:8px;text-align:left;color:var(--text-dim);border-bottom:2px solid var(--border);">Role \\ Action</th>';
    actions.forEach(a => { h += '<th style="padding:8px 6px;text-align:center;color:var(--text-dim);border-bottom:2px solid var(--border);font-weight:600;">'+a+'</th>'; });
    h += '</tr></thead><tbody>';
    roles.forEach((r,ri) => {
      h += '<tr><td style="padding:8px;border-bottom:1px solid var(--border-light);"><strong>'+r.name+'</strong><br><span style="font-size:10px;color:var(--text-light);">'+r.lvl+' · '+r.desc+'</span></td>';
      actions.forEach((a,ai) => {
        const cellOk = allow[ri][ai];
        const sel = (ri===selR && ai===selA);
        const bg = cellOk ? 'rgba(61,139,90,0.12)' : 'rgba(194,84,80,0.12)';
        const fg = cellOk ? '#3d8b5a' : '#c25450';
        const ring = sel ? 'box-shadow:inset 0 0 0 2px '+fg+';' : '';
        h += '<td onclick="window._secSel('+ri+','+ai+')" style="padding:10px 6px;text-align:center;cursor:pointer;border-bottom:1px solid var(--border-light);background:'+bg+';color:'+fg+';font-size:16px;font-weight:700;'+ring+'">'+(cellOk?'✓':'✗')+'</td>';
      });
      h += '</tr>';
    });
    h += '</tbody></table></div>';
    // explanation
    const r = roles[selR], a = actions[selA];
    let msg;
    if (ok) { msg = '<strong>Positive test.</strong> A '+r.name+' ('+r.lvl+') is permitted to "'+a+'". Pick a representative valid '+r.name+' account and confirm access is <strong>granted</strong>.'; }
    else { msg = '<strong>Negative test.</strong> A '+r.name+' ('+r.lvl+') must NOT be able to "'+a+'". Confirm the system <strong>blocks</strong> this unauthorized action — even via a tampered request.'; }
    h += '<div style="margin-top:14px;background:var(--bg-warm);border-radius:8px;padding:14px 18px;border-left:3px solid '+c+';">';
    h += '<div style="font-size:13px;font-weight:600;color:'+c+';margin-bottom:4px;">'+r.name+' → '+a+' : '+(ok?'ALLOW':'DENY')+'</div>';
    h += '<div style="font-size:13px;color:var(--text);line-height:1.7;">'+msg+'</div></div>';
    h += '<div style="margin-top:10px;font-size:12px;color:var(--text-dim);">💡 Equivalence classes: instead of testing every user ID/password, test a few representative valid + invalid users per level.</div>';
    el.innerHTML = h;
  }
  window._secSel = function(ri,ai){ selR=ri; selA=ai; render(); };
  render();
};

// ============================================================
// Unit 7: Structural (Non-Functional) Testing — MODERN NOTES
// Keys are 'unitId-conceptIndex' (0-based). Concept order:
// 0=Learning Obj, 1=What is structural, 2=Why it matters, 3=Why W/B box don't apply,
// 4=Interface, 5=Security, 6=Installation, 7=Administration,
// 8=Backup/Recovery, 9=More NFT types, 10=ISTQB, 11=LA ATC
// ============================================================
MODERN_NOTES['7-1'] = {
  title: 'The "software platform" is now the cloud',
  year: '2026',
  content: 'The platform the book describes is now <strong>cloud-native</strong>: containers (Docker), orchestration (Kubernetes), managed databases, CDNs, and serverless functions. Modern teams validate it continuously with <strong>observability</strong> — metrics, logs, and traces (Datadog, Grafana, OpenTelemetry) — and define quality targets as <strong>SLIs/SLOs with error budgets</strong> (Google SRE). Structural testing didn\'t disappear; it moved into the platform/SRE layer and runs all the time, not once before release.'
};
MODERN_NOTES['7-4'] = {
  title: 'Contract testing & service virtualization replaced manual stubs',
  year: '2026',
  content: 'The book\'s manual "stubbing" is now automated. <strong>Consumer-driven contract testing</strong> (Pact) verifies a service and its callers agree on the API without a full end-to-end environment. <strong>Service virtualization / mocking</strong> (WireMock, Mountebank, Postman mock servers) simulates unavailable platform components on demand — the textbook\'s stub, but reusable and running in CI. Machine-readable specs (OpenAPI/Swagger) let interface validation be generated automatically.'
};
MODERN_NOTES['7-5'] = {
  title: 'DevSecOps: security testing in every pipeline run',
  year: '2026',
  content: 'The book treats security testing as one sub-task. Modern <strong>DevSecOps</strong> makes it continuous: <strong>SAST</strong> (static), <strong>DAST</strong> (dynamic), and <strong>SCA</strong> (dependency scanning) run on <strong>every commit</strong>, alongside secret scanning, container-image scanning, and IaC scanning as build gates. The EU AI Act (2026) and tightening breach-disclosure laws push "security bugs are quality bugs" from slogan to compliance requirement.'
};
MODERN_NOTES['7-6'] = {
  title: 'Installation testing → containers, IaC & canary deploys',
  year: '2026',
  content: '"Run the installer on a production-like box" became <strong>immutable infrastructure</strong>: ship a Docker image, deploy with Kubernetes/Helm, provision with Terraform (Infrastructure as Code). The book\'s rollback is now <strong>blue-green &amp; canary deployments</strong> plus feature flags — release to 1% of traffic, watch the metrics, auto-roll-back on error. GitOps (Argo CD, Flux) makes the whole install reproducible and version-controlled. "Works on my machine" is solved by shipping the machine.'
};
MODERN_NOTES['7-8'] = {
  title: 'Chaos Engineering: intentional failure testing',
  year: '2026',
  content: 'The book\'s backup/recovery testing evolved into <strong>Chaos Engineering</strong> (pioneered by Netflix\'s "Chaos Monkey"). Teams <strong>intentionally inject failures</strong> into production — kill servers, add network latency, corrupt data — to prove the system recovers. Scheduled "game days" and automated resilience drills (Gremlin, AWS Fault Injection Service) turn recovery into a tested routine, instead of a first-time gamble during a real outage.'
};
MODERN_NOTES['7-9'] = {
  title: 'Modern NFT tooling & the rise of SRE',
  year: '2026',
  content: 'Each NFT family now has a mature toolchain: load/reliability with <strong>k6, Gatling, Locust</strong>; usability via analytics + session replay (<strong>Hotjar, FullStory</strong>) and accessibility scanners (axe, Lighthouse); portability via <strong>Docker</strong> (run anywhere) and cross-browser grids (BrowserStack, Playwright). Reliability has become its own discipline — <strong>Site Reliability Engineering (SRE)</strong> — with SLOs, error budgets, and on-call as the modern expression of "does it keep working?"'
};
MODERN_NOTES['7-10'] = {
  title: 'ISTQB added an AI Testing certification',
  year: '2026',
  content: 'ISTQB\'s specialty tracks expanded for the AI era: the <strong>Certified Tester AI Testing (CT-AI)</strong> extension covers testing ML systems, data quality, bias, and using AI to assist testing. Performance Testing and Security Testing specialist certs remain in demand. Foundation Level (<strong>CTFL v4.0</strong>, refreshed 2023) is still the global baseline employers ask for. (See also the ISTQB note in Unit 1.)'
};
MODERN_NOTES['7-11'] = {
  title: 'The 49.7-day bug keeps reappearing',
  year: '2025',
  content: 'Long-uptime integer-overflow bugs are a recurring class. The 2004 LA ATC system died after ~49.7 days (a 32-bit millisecond counter). Echoes: the <strong>Boeing 787</strong> had to be rebooted every 248 days or risk losing electrical power (a 32-bit counter), and the looming <strong>Year 2038 problem</strong> (32-bit Unix time) threatens the same. The fix is what this chapter implies: <strong>long-duration reliability/soak testing</strong> plus tested failover — the structural tests that would have caught every one of them.'
};
