// Unit 9: Testing Environments (Chapter 10, pp.150–158)
EXTRA_UNITS.push({
id:9, concepts:[
{title:"Goal of a Testing Environment",ref:"pp.150–152",content:`<p>A testing environment lets testers observe execution results that the customer will actually experience in production — <strong>before</strong> deployment.</p><p>The goal: cause the application under test to exhibit <strong>true production behavior</strong> while being observed and measured outside production.</p><div class="callout important"><strong>Two critical requirements:</strong><br>1. The environment must <strong>closely mirror production</strong> (hardware, software, network).<br>2. The environment must be under <strong>sole control of the test team</strong>.</div><div class="zh-note">测试环境的目标：在部署前，让软件表现出与生产环境一样的真实行为。必须尽量复制生产环境。</div>`},
{title:"Simulations & Benchmarking",ref:"pp.151–152",content:`<p><span class="key-term">Simulations</span> — Software models that imitate real-world conditions. Useful when the actual production environment isn't available yet.</p><p><span class="key-term">Benchmarking</span> — Running standardized tests to compare performance across different hardware/software configurations. Helps select the best platform before committing resources.</p><p>Questions about the testing environment should arise <strong>very early</strong> in the project — during Preliminary Investigation and Analysis.</p>`},
{title:"Good Testing Environments",ref:"pp.155–156",content:`<p>A <strong>good</strong> testing environment:</p><ul><li>Very closely operates like the production environment (ideally <strong>identical</strong>)</li><li>Is <strong>totally controlled</strong> by the test team</li></ul><p><strong>Benefits of test team control:</strong></p><ol style="padding-left:20px;"><li><span class="key-term">Controlled repeatability</span> — The team knows exactly what software versions and data states are in the environment at all times. Can demonstrate defects to developers on demand.</li><li><span class="key-term">Independence</span> — Testers can plan and execute without interference from development activity.</li></ol><p>No software corrections should be made directly in the testing environment. Changes must go through the same <span class="key-term">staging process</span> as original deployment.</p><div class="zh-note">好的测试环境=尽量和生产环境一样+测试团队完全控制。改代码必须走正式的staging流程。</div>`},
{title:"Bad Testing Environments",ref:"pp.156–157",content:`<p>A <strong>bad</strong> testing environment:</p><ul><li>Only <em>similar</em> to production (not identical)</li><li><strong>Shared</strong> with other teams (developers, training staff)</li></ul><p><strong>Problems with dissimilar environments:</strong></p><ul><li>Faster test computers → misleading performance results (users think it'll be fast)</li><li>Slower test computers → under-reported response times (if it even runs at all)</li><li>Differences in CPU, memory, disk, network, monitors all introduce errors</li></ul><p><strong>Problems with shared environments:</strong></p><ul><li>Test team forced to pause or reschedule when environment is "busy"</li><li>Third-shift (night) testing → testers can't contact anyone at 3 AM to confirm defects, causing delays</li><li><span class="key-term">Rogue software</span> placed by others affects test runs unknowingly → results become non-repeatable</li></ul>`},
{title:"Staging: The Migration Process",ref:"pp.155–157",content:`<p><span class="key-term">Staging</span> = the controlled process of moving software from development to testing (and later to production).</p><p>Good staging uses <strong>automated staging tools</strong> that guarantee:</p><ul><li>Software arriving in testing is the <strong>same</strong> as what departed development</li><li>Each staging is <strong>repeatable</strong></li></ul><div class="callout important"><strong>"Quick fixes" via manual staging</strong> are neither quick nor helpful. Circumventing staging rules is the fastest way to guarantee non-repeatable test results. Companies that allow developers to place untested fixes directly into production are "amazed when the application crashes."</div>`},
{title:"The 'Pay Me Now or Pay Me Later' Axiom",ref:"pp.157–158",content:`<p>The project has <strong>two choices</strong>:</p><ol style="padding-left:20px;"><li><strong>Plan</strong> an appropriate testing environment separate from all other environments → get the best possible test results</li><li><strong>Scrimp</strong> on the testing environment → likely experience customer-discovered defects that cost much more to fix than the environment would have cost</li></ol><div class="callout">When testers get "orphan" hand-me-down equipment, test failures on tester machines can't be recreated on developer machines. Soon <strong>all</strong> test results get dismissed — including the real defects.</div><div class="zh-note">"现在不花钱，以后花更多"——廉价测试环境导致的假失败会让团队连真正的缺陷都不信了。</div>`}
],quiz:[
{type:"mc",q:"The two critical requirements for a good testing environment are:",options:["Fast hardware and latest software","Mirror production and sole test team control","Multiple servers and load balancers","Separate network and cloud hosting"],answer:1,explanation:"A good testing environment closely mirrors production AND is totally controlled by the test team."},
{type:"mc",q:"What is the biggest risk of sharing the testing environment with developers?",options:["Higher hardware costs","Rogue software affecting test runs, making results non-repeatable","Developers fixing too many defects","Tests running too fast"],answer:1,explanation:"Others may place rogue software that unknowingly affects test runs. The first clue: results cannot be repeated."},
{type:"sa",q:"Why should corrections never be made directly in the testing environment?",sampleAnswer:"Modifying previously tested code in the testing environment makes all previous test results null and void. Corrections must be made in the developer's environment and re-staged into testing using the same staging process, so that the test team always knows exactly what versions are being tested and results remain repeatable.",keywords:["null","void","staging","developer","repeatable","versions","control"]},
{type:"mc",q:"Third-shift (night) testing is problematic because:",options:["Computers run slower at night","Testers can't contact anyone at 3 AM to confirm defects","Night electricity costs more","Security systems block access"],answer:1,explanation:"When a tester finds a defect at 3 AM, nobody is available to help. Testing halts until morning — the very delay night testing was supposed to avoid."},
{type:"mc",q:"What does 'staging' refer to in the testing context?",options:["Setting up the testing schedule","The controlled process of moving software from development to testing","Creating test data","Deploying software to customers"],answer:1,explanation:"Staging is the controlled migration of software from development to the testing environment (and later to production) using automated tools."},
{type:"sa",q:"Explain the 'pay me now or pay me later' axiom for testing environments.",sampleAnswer:"The project can either invest in a proper testing environment now (which gives reliable results) or scrimp on it and face customer-discovered defects later that cost much more to diagnose and fix. When testers use inferior equipment, false test failures occur that can't be reproduced on developer machines, causing all test results — including real defects — to be dismissed.",keywords:["invest","proper","scrimp","customer","cost","false","dismissed","real defects"]}
]});

// ============================================================
// Unit 9: Testing Environments
// ============================================================
MODERN_NOTES['9-0'] = {
  title: 'Containers solve the #1 environment problem',
  year: '2026',
  content: 'The book\'s "mirror production" challenge is now solved by <strong>Docker containers</strong> and <strong>Kubernetes</strong>. A Docker image guarantees the <strong>exact same environment</strong> everywhere — dev, test, and production. No more "it works on my machine" problems. <strong>Ephemeral preview environments</strong> (Bunnyshell, Vercel) spin up a complete production-like environment for every pull request, then destroy it after testing.'
};
MODERN_NOTES['9-4'] = {
  title: 'Infrastructure as Code (IaC) automates staging',
  year: '2026',
  content: 'The book\'s manual staging process is now <strong>Infrastructure as Code</strong>: Terraform, Pulumi, or CloudFormation define the entire environment in version-controlled files. Deploying = running a script. Every deployment is <strong>identical and repeatable</strong> by definition. The book\'s "rogue software" problem disappears because environments are rebuilt from scratch each time.'
};
